Ecommerce-Project/college/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.urls.conf import include
from college import views
from django.views.generic.base import RedirectView
urlpatterns = [
    path('home/', views.HomeView.as_view(),name="home"),
    path('allproducts/', views.AllProductsView.as_view()),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    # path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
    path("register/", CustomerRegistrationView.as_view(), name="customerregistration"),
    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),
    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),name="customerorderdetail"),
    path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
    path("search/", SearchView.as_view(), name="search"),
    path('', RedirectView.as_view(url="home/")),



]

Ecommerce-Project/ecom/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from ecom import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('registration.backends.default.urls')),

    path('college/', include('college.urls')),
    path('', RedirectView.as_view(url="college/")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # ye img docs ke liye hai

Ecommerce-Project/college/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# <!----customerprofile.htmlyaha par par status nam ke field me me by default order_receiver likha aa raha haii
#  pr ham chate haii ki ja order way par ho to on the way dikhaye ya order shipped ho to order
# shipped dikhaye  to ye sab admin hi karega to ham ak admin panal banayege jo admin tracker kohandel karega-->

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model): #therd pe ye banaya
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model): #pahle ye module banya
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model): #second ye module banaya
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title



#jab ham product pe click kar rahe haii to product ka details dikh araha haii
#par ab me chahta hu ki product ka images 3 dikhaye jaisa amazon filipcart me hota haii
#to us product se related images ham productimage module me rakhege
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/") #product ke under images nam ki directry me save hoga product tables se related images

    def __str__(self):
        return self.product.title


class Cart(models.Model): #fourth pe ye module banaya haii
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Khalti", "Khalti"),
    ("Esewa", "Esewa"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

Ecommerce-Project/college/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, CreateView, FormView, DetailView, ListView
from college.models import Product, Category, Cart, CartProduct, User, Customer, Order
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from college.forms import CheckoutForm,CustomerRegistrationForm,CustomerLoginForm
from django.db.models import Q


# Create your views here.

#We are Inheriting this class to Other Classes For Renaming Customer Name.
class EcomMixin(object):    
    def dispatch(self, request, *args, **kwargs):
        cart_id = request.session.get("cart_id") #Session Framework is used for Handeling Multiple Users Data--> 'cart_id' key used to Get Data of Html Element cart_id with Unique Session id
        if cart_id: #if cart_id has data then follow the process below
            cart_obj = Cart.objects.get(id=cart_id) #Storing Data In Cart_id key inside cart_obj variable
            if request.user.is_authenticated and request.user.customer:
                #if a user is Authenticated(login) and inside customer table
                cart_obj.customer = request.user.customer #Saving new Items inside cart_obj
                cart_obj.save()
        return super().dispatch(request, *args, **kwargs)




class HomeView(EcomMixin,TemplateView):
    template_name = "college/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['myname'] = "vivek" #All Products are Stored inside Vivek
        all_products = Product.objects.all().order_by("-id")

        paginator = Paginator(all_products, 8) #Limiting Products To 8 Products Per Page
        page_number = self.request.GET.get('page') #Current Page Number
        print(page_number)
        product_list = paginator.get_page(page_number)
        context['product_list'] = product_list
        return context



class AllProductsView(EcomMixin,TemplateView): #All Products in Table are Initially shown in page
    template_name = "college/allproducts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['allcategories'] = Category.objects.all()
        return context

class ProductDetailView(EcomMixin,TemplateView): #Shows Product Details On Clicking Product At Home Page
    template_name = "college/product_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        url_slug = self.kwargs['slug']
        product = Product.objects.get(slug=url_slug)
        product.view_count += 1
        product.save()
        context['product'] = product
        return context




class AddToCartView(EcomMixin,TemplateView):
    template_name = "college/addtocart.html" #Cart html Page Object
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # get product id from requested url
        product_id = self.kwargs['pro_id'] #Store Product Ids inside product_id from **kwargs dict
        # Initiallizing Product_obj with Product_id key data
        product_obj = Product.objects.get(id=product_id)
        # check if cart contain item added inside in Page
        cart_id = self.request.session.get("cart_id", None)
        if cart_id: #if cart_id is not None  
            cart_obj = Cart.objects.get(id=cart_id)
            #Finding Products inside Product Table
            this_product_in_cart = cart_obj.cartproduct_set.filter(product=product_obj)

            # item already exists in cart
            if this_product_in_cart.exists():
                cartproduct = this_product_in_cart.last()

                cartproduct.quantity += 1
                cartproduct.subtotal += product_obj.selling_price
                cartproduct.save()
                cart_obj.total += product_obj.selling_price
                cart_obj.save()
            # new item is added in cart

            else:
                #if cart_id not exist then insert inside `cart_name` table
                cartproduct = CartProduct.objects.create(cart=cart_obj, product=product_obj, rate=product_obj.selling_price, quantity=1, subtotal=product_obj.selling_price)
                cart_obj.total += product_obj.selling_price
                cart_obj.save()

        else: #If same cart added again
            cart_obj = Cart.objects.create(total=0)
            self.request.session['cart_id'] = cart_obj.id
            cartproduct = CartProduct.objects.create(
                cart=cart_obj, product=product_obj, rate=product_obj.selling_price, quantity=1, subtotal=product_obj.selling_price)
            cart_obj.total += product_obj.selling_price
            cart_obj.save()

        return context


class MyCartView( EcomMixin,TemplateView): #Template For Cart
    template_name = "college/mycart.html"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
        else:
            cart = None
        context['cart'] = cart
        return context


class ManageCartView(EcomMixin,View): #Management For Cart Items Addition and Removal
    def get(self, request, *args, **kwargs):
        cp_id = self.kwargs["cp_id"]  # Fetching Card Id
        action = request.GET.get("action")  # Getting Action From Html Page
        cp_obj = CartProduct.objects.get(id=cp_id)
        cart_obj = cp_obj.cart

        if action == "inc": #increase item Purchased
            cp_obj.quantity += 1
            cp_obj.subtotal += cp_obj.rate
            cp_obj.save()
            cart_obj.total += cp_obj.rate
            cart_obj.save()

        elif action == "dcr":  #decrease item Purchased
            cp_obj.quantity -= 1
            cp_obj.subtotal -= cp_obj.rate
            cp_obj.save()
            cart_obj.total -= cp_obj.rate
            cart_obj.save()
            if cp_obj.quantity == 0:
                cp_obj.delete()

        elif action == "rmv":  #remove item Purchased
            cart_obj.total -= cp_obj.subtotal
            cart_obj.save()
            cp_obj.delete()
        else:
            pass
        return redirect("mycart")



class EmptyCartView(EcomMixin,View):                   #To Empty the cart
    def get(self, request, *args, **kwargs):
        cart_id = request.session.get("cart_id", None) #If cart id not present Then Initiallize None
        if cart_id:                                    #If cart_id is Not None

            cart = Cart.objects.get(id=cart_id) #Storing Data of Select * from `cart` where cart_id=cart_id;   
            cart.cartproduct_set.all().delete() #Deleting all Products which are inside producy table
            cart.total = 0
            cart.save()
        return redirect("mycart")


class CheckoutView(EcomMixin,CreateView):
    template_name = "college/checkout.html"
    form_class = CheckoutForm           #importing checkoutform class from form.py file 
    success_url = reverse_lazy("home")  #Redirecting to the home page after cheackout successful
    #if the user is not login the he/she redirected to login page

    def dispatch(self, request, *args, **kwargs): #whenever user request then method will be exicuted
        print("hello iam dispatch method")
        if request.user.is_authenticated and request.user.customer:
            print("login user")                   #This message is printed when user is login
            pass
        else:
            print("not login user")
            return redirect("/college/login/?next=/checkout/") #redirect the user to login page if not login
        return super().dispatch(request, *args, **kwargs)




    def get_context_data(self, **kwargs): #inserting cart data to dict cart
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
        else:
            cart_obj = None
        context['cart'] = cart_obj
        return context


    def form_valid(self, form): 
        cart_id = self.request.session.get("cart_id") #cart_id contain session data
        if cart_id: #If cart_id contain data then following code execute
            cart_obj = Cart.objects.get(id=cart_id)  #Only the data whose cart_id match the Cart_id is accessed
            form.instance.cart = cart_obj #cart_obj data will be insert inserted to fields = ["ordered_by", "shipping_address", "mobile", "email", "payment_method"]
            form.instance.subtotal = cart_obj.total #insert the total amount to the subtotal field 
            form.instance.discount = 0 #discount field is 0 bydefayult
            form.instance.total = cart_obj.total #total field has same data as of total field contains 
            form.instance.order_status = "Order Received" #bydefault orderstatus is Order Recieved
            del self.request.session['cart_id'] #delete session after checkout the data

            

        else:
            return render("mycart") #redirects to mycart after database insertion completed
        return super().form_valid(form)





#payment getway lagane ka logik haiii
class KhaltiRequestView(View): #yaha se redirwct hohga khaltirequest.html page pe
    def get(self, request, *args, **kwargs):
        # o_id = request.GET.get("o_id") # khalti-request page par Your order amount is Rs.ke  bhi age order product ka total  likha aana chahiye
        # order = Order.objects.get(id=o_id) #bs is liye ye logik likha haii
        context = {
            # "order": order #Your order amount is Rs. 70000 aisa print hoga khalti-request page pe

        }
        return render(request, "college/khaltirequest.html", context)


#
# class KhaltiVerifyView(View):

Ecommerce-Project/college/templates/college/addtocart.html
{% extends 'base.html' %}

{% block title %}Add to cart{% endblock %}

{% block content %}
<div class="container">
    <h3>Product added to cart successfully.</h3>
</div>
{% endblock %}

Ecommerce-Project/college/templates/college/allproducts.html
{% extends 'base.html' %}
{% block content %}




<div class="container">
    <h3>All Products</h3><hr>

    {% for cat in allcategories %}
    <h4>{{cat.title}}</h4><hr>
          <div class="row">
          <!---  iska matlab ki mere pass allcatogary ko mene cat nam ke variable me liya haii
            ab mene ak p variables banaya or cat.product_set.all ye likha iska matlab samjoki cat nam ke variables
             me jitne bhi category haii or product nam ke tables me jitne bhi foregn key bana haii catogry matlab jo jo product electronics
             ke haii o electronics catogy ke niche dikhaye or jitne bhi product fashon-cloth ke haii o sab fashion cloth category ke niche show-->
        {% for p in cat.product_set.all %}
        <div class="col-md-3 card">
            <div class="m-4">
                <h4><a href="">{{p.title}}</a></h4>
                <img src="/media/{{p.image}}" class="card-img-top" alt="..." style="height:200px">
                 <p class="mt-3">Price: <strike>Rs. {{p.marked_price}}</strike> Rs. {{p.selling_price}}</p>
                 <a href="" class="btn btn-primary w-100">Add To Cart</a>
            </div>
        </div>
        {% endfor %}
    </div>


       {% endfor %}
</div>

{% endblock %}

Ecommerce-Project/college/templates/college/checkout.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Items in the cart</h3>
            <a href="{% url 'mycart' %}">Update Cart</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <!---ham yaha par django ka inbult form used kar sake haii to me form.py nam ka ak python banauga -->
                <button class="btn btn-info">Place order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Ecommerce-Project/college/templates/college/customerlogin.html
{% extends 'base.html' %}



{% block content %}
<style>
    .errorlist {
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Login Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Login as a Customer</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
             <p>Forgot Password?<a href="{% url 'passworforgot' %}">Reset now.</a></p>
          <p> or dont have account? <a href="{% url 'customerregistration' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Register here</a></p>
        </div>
    </div>
</div>
{% endblock %}

Ecommerce-Project/college/templates/college/customerorderdetail.html
{% extends "base.html" %}
{% load humanize %}
<!---hamne load humanize ko install kiya hai settings.py file me or yaha usko load kiya haii ye sirf
 itna kam karega ki jo hamara last me total haii (|intcomma) or aisa likha haii
  par jab ham load humanize ko load karte haii to aisa likhte hi haii
  to iska out put aisa aayega ki total=70000/- aisa na likhte huye 70,000 aisa ammount show hoga
   ex= 130000 aisa total haii to load humanize ki wajah se 1,30,000 aise show hoga-->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>Order Detail</h3><hr>
             <p><span class="font-weight-bold">Order ID: </span> #ORDER_{{ord_obj.id}}</p>
            <p><span class="font-weight-bold">Order Status: </span> {{ord_obj.order_status}}</p>
            <p><span class="font-weight-bold">Order On: </span> {{ord_obj.created_at}}({{ord_obj.created_at|timesince}} ago)</p>
            <p><span class="font-weight-bold">Customer Information: </span> By {{ord_obj.ordered_by}}, {{ord_obj.mobile}}</p>
            <p><span class="font-weight-bold">Shipping Address: </span> By {{ord_obj.shipping_address}} ({{ord_obj.email}})</p>

        <h4>Ordered Items</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in ord_obj.cart.cartproduct_set.all %}

                    <!--- kyo ki jab data addtocart hota haii to cart nam ke tbale me
                    login user ka nam customer field me ja raha haii or total field me us addtocart kiye product ka total price ja raha haii
                    usi time cartproduct name ke tables me jo user ne addtocart kiya haii uska cart field me cart ki id
                     product ka nam rate quentity or subtotal insert ho jayega or cart product ka sara data view cart wale html page
                     me sho karega jab ham ab is data ko urder karne ke liye checkout par click karege to ak checkout.html page pe
                     jayega jaha hamko form fill kar ke order place karna haii or place order ka data order wale table me insert hoga
                     or yahi order tables ka data hamko fetch hoke myprofile wale page dikhege par hamne aisa logik lagaya haii
                     ki jo user login haii or usne jo data order kiya haii usko usi ka data dikhaye

                     for cp in ord_obj.cart.cartproduct_set.all -->
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a target="_blank" href="{% url 'productdetail' cp.product.slug %}">{{cp.product.title}}({{cp.product.id}})</a></td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total: </th>
                         <th>Rs {{ord_obj.total|intcomma}}/-</th>



                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

Ecommerce-Project/college/templates/college/customerprofile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Detail Information</h3><hr>
             <p><span class="font-weight-bold">Name: </span> {{customer.full_name}}</p>
            <p><span class="font-weight-bold">Username: </span> {{customer.user.username}}</p>
            <p><span class="font-weight-bold">Email: </span> {{customer.user.email}}</p>
            <p><span class="font-weight-bold">Address: </span> {{customer.address}}</p>
            <p><span class="font-weight-bold">Joined on: </span> {{customer.joined_on}}</p>

        </div>
         <div class="col-md-8">
            <h3>Previous Orders</h3>
              <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID</th>
                        <th>Amount</th>
                        <th>Ordered on</th>
                        <th>Status</th>
                        <!----customerprofile.htmlyaha par par status nam ke field me me by default order_receiver likha aa raha haii
                         pr ham chate haii ki ja order way par ho to on the way dikhaye ya order shipped ho to order
                         shipped dikhaye  to ye sab admin hi karega to ham ak admin panal banayege jo admin tracker kohandel karega-->
                    </tr>
                </thead>
                <tbody>
                    {% for ord in orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <!---order_id order tbales se fetch ho rahi haii-->
                        <td><a href="{% url 'customerorderdetail' ord.pk %}"> #ORDER_{{ord.id}}</a></td>
                        <td>{{ord.total}}</td>
                        <td>{{ord.created_at|timesince}} ago</td>
                        <td>{{ord.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>


    </div>
    </div>
</div>


{% endblock %}

Ecommerce-Project/college/templates/college/customerregistration.html
{% extends 'base.html' %}
{% block content %}
<style>
    .errorlist{
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Registration Form</h3><hr>
             <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Register as a Customer</button>
            </form>
            <p> Already have an account? <a href="{% url 'customerlogin' %}">Login here</a></p>

        </div>
    </div>
</div>
{% endblock %}

Ecommerce-Project/college/templates/college/home.html
{% extends 'base.html' %}

{% block content %}


<h4 class="text-center mt-3">Welcome To My Ecommerce Website</h4>
<div class="container mt-4">
    <div class="row">
{% for n1 in product_list %}
        <div class="col-md-3">

<div class="card w-90 h-100 text-center" style="width: 14rem;">
     <div class="card-body">
     <h5 class="card-title"><a href="{% url 'productdetail' n1.slug %}">{{n1.title}}</a></h5>
  <img src="/media/{{n1.image}}" class="card-img-top" alt="..." style="height:200px">


    <p class="mt-3">Price: <strike>Rs. {{n1.marked_price}}</strike> Rs. {{n1.selling_price}}</p>

    <a href="{% url 'addtocart'  n1.id %}" class="btn btn-primary w-100">Add To Cart</a>
  </div>
</div>
        </div>
        {% endfor  %}

</div>
</div>
<!---ye pagination ka code haii-->
<div class="">
 <nav aria-label="...">
        <ul class="pagination">
            {% if product_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ product_list.previous_page_number }}">Previous</a>
              </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            {% endif %}

            {% for i in product_list.paginator.page_range %}
            {% if i == product_list.number %}
            <li class="page-item active"><a class="page-link">{{i}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}

            {% if product_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ product_list.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
            {% endif %}
        </ul>
      </nav>

</div>
{% endblock %}

Ecommerce-Project/college/templates/college/khaltirequest.html
kdnfj

Ecommerce-Project/college/templates/college/product_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h3>Product: {{product.title}}</h3><hr>
    <div class="row">
        <div class="col-md-4">
        <img src="/media/{{product.image}}" class="card-img-top" alt="...">

         <div class="row">
             <!----product folder me ak or folder haii images jisme product re related images haii
             hamko product tables se productimages nam ki tables me jo images haii usko fetch karna haii--->
                {% for pi in product.productimage_set.all %}
                <div class="col-md-4 p-3">
                    <a href="{{pi.image.url}}" target="_blank">
                        <img src="{{pi.image.url}}" class="img-fluid" style="height: 100px; object-fit: contain;" alt="">
                    </a>
                </div>
                {% endfor %}
            </div>

        </div>
           <div class="col-md-8">
            <h4>{{product.title}} (Viewed {{product.view_count}} times)</h4>
            <h5>Category: {{product.category}}</h5>
            <h5>Price: <strike>Rs. {{product.marked_price}}</strike> Rs. {{product.selling_price}}</h5>
            <a  class="btn btn-info">Add To Cart</a>
            <hr>
            <p class="text-info">Warranty: {{product.warranty}}</p>
            <p class="text-info">Return Policy:{{product.return_policy}}</p>
            <hr>
            <p>{{product.description}}</p>
        </div>
    </div>

</div>
</div>

{% endblock %}

Ecommerce-Project/college/templates/college/search.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for <span class="text-info">"{{request.GET.keyword}}"</span></h3>
            <hr>
            {% for result in results %}
            <div class="row">
                <div class="col-md-3">
                    <img src="{{result.image.url}}" class="img-fluid" alt="">
                </div>
                <div class="col-md-9">
                    <h4><a href="{% url 'productdetail' result.slug %}">{{result.title}}</a></h4>
                    <p>{{result.description|truncatewords:50}}</p>
                    <p>Return Policy: {{result.return_policy}}</p>
                    <a href="{% url 'addtocart' result.id %}" class="btn btn-primary">Add To Cart</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}